[project]
name = "elo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.3",
    "langchain>=1.0.8",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.0.3",
    "openai>=2.8.1",
    "pyngrok>=7.5.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "python-telegram-bot>=21.0",
    "requests>=2.32.5",
    "twilio>=9.8.7",
    "uvicorn>=0.38.0",
]
